### ISSUE TITLE
L'application ne fonctionne pas avec des téléphones Iphone

### ISSUE THREAD

**Issue by guironne** [seb-cogez/QCMCam#5]
L'application ne fonctionne pas avec des téléphones Iphone

**Comment by seb-cogez** [comment]
Si, mais il faut donner les droits qu'il faut au site dans safari.
[https://youtube.com/shorts/1JmrKRbrcTc](https://youtube.com/shorts/1JmrKRbrcTc)
Cordialement

**Comment by seb-cogez** [comment]
Si vous donnez toujours les droits d'accès au site à la  camera en cliquant sur aA, les deux cameras sont détectées après rechargement. Il faut ensuite changer de camera à l'aide du bouton vert sur l'iphone/ipad pour que la bonne caméra soit utilisée.
Quand j'aurai le temps je testerai pour voir le nom de la camera frontale sur ipad.
