### ISSUE TITLE
Typo/Error in sessiondispo.php leading to Server Error 500

### ISSUE THREAD

**Issue by complanar** [seb-cogez/QCMCam#8]
In `sessiondispo.php` in line 18 there are quotes missing. Instead of `$_SESSION[idsession]` there must be `$_SESSION['idsession']`. This can lead to a internal Server Error depending on how PHP is configured.

**Comment by seb-cogez** [comment]
Effectivement une grossière erreur de ma part,
Merci pour le retour, j'ai corrigé.
